name       : openmw
version    : 0.45.0
release    : 23
source     :
    - https://github.com/OpenMW/openmw/archive/openmw-0.45.0.tar.gz : b63cf971f406ef5f28019f65e9e2bd9641a227459ede45d147562917f67e1c64
license    : GPL-3.0-or-later
component  : games.rpg
summary    : OpenMW is a recreation of the engine for the popular role-playing game
    Morrowind by Bethesda Softworks
description: |
    OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
builddeps  :
    - pkgconfig(MYGUI)
    - pkgconfig(Qt5Core)
    - pkgconfig(bullet)
    - pkgconfig(libavcodec)
    - pkgconfig(libunshield)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(sdl2)
    - pkgconfig(tinyxml)
    - pkgconfig(xt)
    - libboost-devel
optimize   : lto
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-build-errors-with-MyGUI-3.4.0.patch
    sed -i "s|games/||" CMakeLists.txt

    %cmake_ninja \
        -DDESIRED_QT_VERSION=5 \
        -DUSE_SYSTEM_TINYXML=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
