name       : openmw
version    : 0.47.0
release    : 35
source     :
    - https://github.com/OpenMW/openmw/archive/refs/tags/openmw-0.47.0.tar.gz : bd7f77e1527c2180e9b0dfcbe401d6fb48f24dbb37701dac7747697873d6edb4
license    : GPL-3.0-or-later
component  : games.rpg
summary    : OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
description: |
    OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
builddeps  :
    - pkgconfig(MYGUI)
    - pkgconfig(Qt5Core)
    - pkgconfig(bullet)
    - pkgconfig(libavcodec)
    - pkgconfig(liblz4)
    - pkgconfig(libunshield)
    - pkgconfig(openscenegraph)
    - pkgconfig(openal)
    - pkgconfig(recastnavigation)
    - pkgconfig(sdl2)
    - pkgconfig(tinyxml)
    - pkgconfig(xt)
    - libboost-devel
optimize   : lto
setup      : |
    sed -i "s|games/||" CMakeLists.txt
    %patch -p1 < $pkgfiles/glibc-2.34.patch
    %patch -p1 < $pkgfiles/missing-include.patch

    %cmake_ninja \
        -DDESIRED_QT_VERSION=5 \
        -DOPENMW_USE_SYSTEM_RECASTNAVIGATION=ON \
        -DUSE_SYSTEM_TINYXML=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/licenses/
