name       : openmw
version    : 0.46.0
release    : 28
source     :
    - https://github.com/OpenMW/openmw/archive/openmw-0.46.0.tar.gz : 07a35a8f15f67f5aa7210c2a307a6db5660a9b61fe34983c35b172c8671afd58
license    : GPL-3.0-or-later
component  : games.rpg
summary    : OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
description: |
    OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
builddeps  :
    - pkgconfig(MYGUI)
    - pkgconfig(Qt5Core)
    - pkgconfig(bullet)
    - pkgconfig(libavcodec)
    - pkgconfig(libunshield)
    - pkgconfig(openscenegraph)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(tinyxml)
    - pkgconfig(xt)
    - libboost-devel
optimize   : lto
setup      : |
    sed -i "s|games/||" CMakeLists.txt

    %cmake_ninja \
        -DDESIRED_QT_VERSION=5 \
        -DUSE_SYSTEM_TINYXML=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
