name       : openmw
version    : 0.43.0
release    : 10
source     :
    - https://github.com/OpenMW/openmw/archive/openmw-0.43.0.tar.gz : c4f0258d35fe1c181c2c609658467e1560ce262d02bf5e92b064d7b14e97f086
license    : GPL-3.0
component  : games.rpg
summary    : OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
description: |
    OpenMW is a recreation of the engine for the popular role-playing game Morrowind by Bethesda Softworks
builddeps  :
    - pkgconfig(bullet)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libunshield)
    - pkgconfig(Qt5Core)
    - pkgconfig(MYGUI)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(sdl2)
    - pkgconfig(tinyxml)
    - pkgconfig(xt)
    - gtest-devel
    - libboost-devel
setup      : |
    sed -i "s|games/||" CMakeLists.txt
    %cmake -DDESIRED_QT_VERSION=5 \
           -DLIBDIR=%libdir% \
           -DBUILD_UNITTESTS=ON \
           -DUSE_SYSTEM_TINYXML=ON \
           .
build      : |
    %make
install    : |
    %make_install
check      : |
    ./openmw_test_suite
